### ISSUE TITLE
Problem in example

### ISSUE THREAD

**Issue by drJfunk** [jmeyers314/linmix#13]
Hello,

I'm just trying to duplicate you example. The fitting itself seems to work, however, the production of the sample does not. Perhaps I am misinterpreting something?

Should the following lines:
x = np.random.normal(loc=xi, scale=xsig)
y = np.random.normal(loc=xi, scale=ysig)

be:
x = np.random.normal(loc=xi, scale=xsig)
y = np.random.normal(loc=eta, scale=ysig)

Even this change does not seem to duplicate the desired simulation data.

**Comment by jmeyers314** [comment]
Hi @drJfunk ,

It looks like you're looking at the tests/test.py script?  I wrote this to directly compare the python and IDL versions of linmix.  On my test computer, the samples outputs look very similar (you can use the plottest.py, triangle_test.py, and chain_plot.py scripts to compare the python/IDL outputs).

Are you working from the latest commit on the master branch?  I think I've already fixed the typo you've pointed out.

Can you be more specific about what's not being correctly duplicated in the simulation data?

Thanks

**Comment by drJfunk** [comment]
Ah, yes you are correct. In the test folder it is correct. I was looking at the pydocs online (http://linmix.readthedocs.org/en/latest/example.html) and the typo was still there, but now everything makes sense. Thanks!

**Comment by jmeyers314** [comment]
Okay, I see now.  You're right, this a bug in the pydocs.  Just committed a fix (and corrected a couple other typos as well).  Hopefully the example will work now; let me know if not.  Thanks for the note!

-Josh

**Comment by drJfunk** [comment]
It works :) thanks!



/J. Michael 

- sent from my iPhone




+46 72 381 3020
