### ISSUE TITLE
what to use for censored data point errors that do not have an error value

### ISSUE THREAD

**Issue by paigemkelly** [jmeyers314/linmix#26]
I have censored data points that are 3sigma upper limits. I have no error values for these points but linmix is not running with no error value assigned. Does anyone know what to use for error in this situation?

**Comment by theodorostopkaras** [comment]
Hello, 
Can you tell me how you solved this issue? I have also values that also lack error values (I have assigned the errors to 0, so basically the code gives me an error).

**Comment by paigemkelly** [comment]
Hi,
I ended up setting the error to 0. If I remember correctly, I tried a few error values and it did not change the result at all. I would double check that though.
